### ISSUE TITLE
Spring Managed Consumer Interceptors

### ISSUE THREAD

**Issue by frosiere** [spring-projects/spring-kafka#2244]
Following https://github.com/spring-projects/spring-kafka/issues/2049, 
Spring Kafka may also support Spring managed interceptors for standard consumers and streams.

In pure Kafka, interceptors can be specified through a configuration entry. This entry contains the list of classes related to the interceptors. This list of class is then converted into a list of interceptor instances (see AbstractConfig#getConfiguredInstances). As the interceptor is instantiated by Kafka itself, there is no way to inject dependencies into the interceptor expect by using the trick with the configure method (see https://docs.spring.io/spring-kafka/docs/current/reference/html/#interceptors). Would be great if Kafka could support instances instead of classes (technical limitation?).

So, the proposal would be to extend ProducerConfig, ConsumerConfig and StreamsConfig as follow to complete the list of interceptors with the Spring managed interceptors.
```
// example for streams
public class SpringAwareStreamConfig extends StreamsConfig {

    private final List<ProducerInterceptor<?, ?>> producerInterceptors;
    private final List<ConsumerInterceptor<?, ?>> consumerInterceptors;

    public SpringAwareStreamConfig(Map<?, ?> props,
                                   boolean doLog,
                                   List<ProducerInterceptor<?, ?>> producerInterceptors,
                                   List<ConsumerInterceptor<?, ?>> consumerInterceptors) {
        super(props, doLog);
        this.producerInterceptors = producerInterceptors;
        this.consumerInterceptors = consumerInterceptors;
    }

    @Override
    public <T> List<T> getConfiguredInstances(List<String> classNames, Class<T> t, Map<String, Object> configOverrides) {
        final var configuredInstances = super.getConfiguredInstances(classNames, t, configOverrides);
        if (ConsumerInterceptor.class.equals(t)) {
            configuredInstances.addAll((Collection<? extends T>) consumerInterceptors);
        }
        if (ProducerInterceptor.class.equals(t)) {
            configuredInstances.addAll((Collection<? extends T>) consumerInterceptors);
        }
        return configuredInstances;
    }
}
```
These new Kafka config classes would then be respectively instantiated in

- DefaultKafkaProducerFactory#createRawProducer
- DefaultKafkaConsumerFactory#createRawConsumer
- StreamsBuilderFactoryBean#start

Any comment, feedback, other proposal is more than welcome.

**Comment by garyrussell** [comment]
Interesting; I was not aware of those methods; much better than the hack in the docs you referenced.

Sounds like a plan. Looking forward to seeing a PR.

**Comment by frosiere** [comment]
Unfortunately, the proposal I did is not applicable for producers and consumers as the constructor accepting a producer/consumer config is not public (default modifier).
Issue has been created on the Kafka project to increase the visibility of this constructor.
See https://issues.apache.org/jira/browse/KAFKA-13864

Remark: for the producer, a custom config would not be required as the new constructor already accept a list of interceptors
See https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/producer/KafkaProducer.java#L326. Exposing this constructor may also simplify a lot the implementation made in #2049 

I could still drop a PR for streams but this would be incomplete.

**Comment by sobychacko** [comment]
@frosiere, that Kafka Jira issue is now resolved. Do you happen to have any updates on this issue? Thanks!

**Comment by frosiere** [comment]
@sobychacko, I'm afraid this issue cannot be resolved, as Kafka's limitation is still present.
A KIP would be necessary to justify this need. I tried in the past, but stopped due to other activities.

**Comment by sobychacko** [comment]
Thanks for the response. This issue has been around for 3 years now. I was in the process of cleaning up the backlog and wanted to know if we could address it. What's the outlook? Are there any workarounds that come to mind?
